name: Build & Deploy Golang App

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: english-app:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout source
        uses: actions/checkout@v3

      - name: 🔐 Login to Self-hosted Docker Registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_HOST }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: 🛠️ Build and Push Docker image
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: 🔐 Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 🚀 Deploy on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << EOF
            docker login ${{ secrets.REGISTRY_HOST }} -u ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }}
            docker pull $IMAGE_NAME
            cd ~/myapp
            docker compose up -d
          EOF
